// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/hwameistor/local-storage/pkg/apis/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// LocalStorageAlerts returns a LocalStorageAlertInformer.
	LocalStorageAlerts() LocalStorageAlertInformer
	// LocalStorageNodes returns a LocalStorageNodeInformer.
	LocalStorageNodes() LocalStorageNodeInformer
	// LocalVolumes returns a LocalVolumeInformer.
	LocalVolumes() LocalVolumeInformer
	// LocalVolumeExpands returns a LocalVolumeExpandInformer.
	LocalVolumeExpands() LocalVolumeExpandInformer
	// LocalVolumeReplicas returns a LocalVolumeReplicaInformer.
	LocalVolumeReplicas() LocalVolumeReplicaInformer
	// PhysicalDisks returns a PhysicalDiskInformer.
	PhysicalDisks() PhysicalDiskInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// LocalStorageAlerts returns a LocalStorageAlertInformer.
func (v *version) LocalStorageAlerts() LocalStorageAlertInformer {
	return &localStorageAlertInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalStorageNodes returns a LocalStorageNodeInformer.
func (v *version) LocalStorageNodes() LocalStorageNodeInformer {
	return &localStorageNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumes returns a LocalVolumeInformer.
func (v *version) LocalVolumes() LocalVolumeInformer {
	return &localVolumeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeExpands returns a LocalVolumeExpandInformer.
func (v *version) LocalVolumeExpands() LocalVolumeExpandInformer {
	return &localVolumeExpandInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeReplicas returns a LocalVolumeReplicaInformer.
func (v *version) LocalVolumeReplicas() LocalVolumeReplicaInformer {
	return &localVolumeReplicaInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// PhysicalDisks returns a PhysicalDiskInformer.
func (v *version) PhysicalDisks() PhysicalDiskInformer {
	return &physicalDiskInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
