apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localvolumeconverts.hwameistor.io
spec:
  group: hwameistor.io
  names:
    kind: LocalVolumeConvert
    listKind: LocalVolumeConvertList
    plural: localvolumeconverts
    shortNames:
    - lvconvert
    singular: localvolumeconvert
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Name of the volume to convert
      jsonPath: .spec.volumeName
      name: volume
      type: string
    - description: Number of volume replica
      jsonPath: .spec.replicaNumber
      name: replicas
      type: integer
    - description: State of the expansion
      jsonPath: .status.state
      name: state
      type: string
    - description: Event message of the expansion
      jsonPath: .status.message
      name: message
      type: string
    - description: Abort the operation
      jsonPath: .spec.abort
      name: abort
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: LocalVolumeConvert is the Schema for the localvolumeconverts
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LocalVolumeConvertSpec defines the desired state of LocalVolumeConvert
            properties:
              abort:
                default: false
                type: boolean
              replicaNumber:
                description: ReplicaNumber is the number of replicas which the volume
                  will be converted to currently, only support the case of converting
                  a non-HA volume to HA
                format: int64
                maximum: 2
                minimum: 2
                type: integer
              volumeName:
                type: string
            type: object
          status:
            description: LocalVolumeConvertStatus defines the observed state of LocalVolumeConvert
            properties:
              message:
                type: string
              state:
                description: State is state type of resources
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
