// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/hwameistor/hwameistor/pkg/apis/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Events returns a EventInformer.
	Events() EventInformer
	// LocalDisks returns a LocalDiskInformer.
	LocalDisks() LocalDiskInformer
	// LocalDiskActions returns a LocalDiskActionInformer.
	LocalDiskActions() LocalDiskActionInformer
	// LocalDiskClaims returns a LocalDiskClaimInformer.
	LocalDiskClaims() LocalDiskClaimInformer
	// LocalDiskNodes returns a LocalDiskNodeInformer.
	LocalDiskNodes() LocalDiskNodeInformer
	// LocalDiskVolumes returns a LocalDiskVolumeInformer.
	LocalDiskVolumes() LocalDiskVolumeInformer
	// LocalStorageNodes returns a LocalStorageNodeInformer.
	LocalStorageNodes() LocalStorageNodeInformer
	// LocalVolumes returns a LocalVolumeInformer.
	LocalVolumes() LocalVolumeInformer
	// LocalVolumeConverts returns a LocalVolumeConvertInformer.
	LocalVolumeConverts() LocalVolumeConvertInformer
	// LocalVolumeExpands returns a LocalVolumeExpandInformer.
	LocalVolumeExpands() LocalVolumeExpandInformer
	// LocalVolumeGroups returns a LocalVolumeGroupInformer.
	LocalVolumeGroups() LocalVolumeGroupInformer
	// LocalVolumeMigrates returns a LocalVolumeMigrateInformer.
	LocalVolumeMigrates() LocalVolumeMigrateInformer
	// LocalVolumeReplicas returns a LocalVolumeReplicaInformer.
	LocalVolumeReplicas() LocalVolumeReplicaInformer
	// LocalVolumeSnapshots returns a LocalVolumeSnapshotInformer.
	LocalVolumeSnapshots() LocalVolumeSnapshotInformer
	// LocalVolumeSnapshotRestores returns a LocalVolumeSnapshotRestoreInformer.
	LocalVolumeSnapshotRestores() LocalVolumeSnapshotRestoreInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Events returns a EventInformer.
func (v *version) Events() EventInformer {
	return &eventInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalDisks returns a LocalDiskInformer.
func (v *version) LocalDisks() LocalDiskInformer {
	return &localDiskInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalDiskActions returns a LocalDiskActionInformer.
func (v *version) LocalDiskActions() LocalDiskActionInformer {
	return &localDiskActionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalDiskClaims returns a LocalDiskClaimInformer.
func (v *version) LocalDiskClaims() LocalDiskClaimInformer {
	return &localDiskClaimInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalDiskNodes returns a LocalDiskNodeInformer.
func (v *version) LocalDiskNodes() LocalDiskNodeInformer {
	return &localDiskNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalDiskVolumes returns a LocalDiskVolumeInformer.
func (v *version) LocalDiskVolumes() LocalDiskVolumeInformer {
	return &localDiskVolumeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalStorageNodes returns a LocalStorageNodeInformer.
func (v *version) LocalStorageNodes() LocalStorageNodeInformer {
	return &localStorageNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumes returns a LocalVolumeInformer.
func (v *version) LocalVolumes() LocalVolumeInformer {
	return &localVolumeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeConverts returns a LocalVolumeConvertInformer.
func (v *version) LocalVolumeConverts() LocalVolumeConvertInformer {
	return &localVolumeConvertInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeExpands returns a LocalVolumeExpandInformer.
func (v *version) LocalVolumeExpands() LocalVolumeExpandInformer {
	return &localVolumeExpandInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeGroups returns a LocalVolumeGroupInformer.
func (v *version) LocalVolumeGroups() LocalVolumeGroupInformer {
	return &localVolumeGroupInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeMigrates returns a LocalVolumeMigrateInformer.
func (v *version) LocalVolumeMigrates() LocalVolumeMigrateInformer {
	return &localVolumeMigrateInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeReplicas returns a LocalVolumeReplicaInformer.
func (v *version) LocalVolumeReplicas() LocalVolumeReplicaInformer {
	return &localVolumeReplicaInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeSnapshots returns a LocalVolumeSnapshotInformer.
func (v *version) LocalVolumeSnapshots() LocalVolumeSnapshotInformer {
	return &localVolumeSnapshotInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// LocalVolumeSnapshotRestores returns a LocalVolumeSnapshotRestoreInformer.
func (v *version) LocalVolumeSnapshotRestores() LocalVolumeSnapshotRestoreInformer {
	return &localVolumeSnapshotRestoreInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
