// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalVolumeConverts implements LocalVolumeConvertInterface
type FakeLocalVolumeConverts struct {
	Fake *FakeHwameistorV1alpha1
}

var localvolumeconvertsResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localvolumeconverts"}

var localvolumeconvertsKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalVolumeConvert"}

// Get takes name of the localVolumeConvert, and returns the corresponding localVolumeConvert object, and an error if there is any.
func (c *FakeLocalVolumeConverts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localvolumeconvertsResource, name), &v1alpha1.LocalVolumeConvert{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeConvert), err
}

// List takes label and field selectors, and returns the list of LocalVolumeConverts that match those selectors.
func (c *FakeLocalVolumeConverts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeConvertList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localvolumeconvertsResource, localvolumeconvertsKind, opts), &v1alpha1.LocalVolumeConvertList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalVolumeConvertList{ListMeta: obj.(*v1alpha1.LocalVolumeConvertList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalVolumeConvertList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localVolumeConverts.
func (c *FakeLocalVolumeConverts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localvolumeconvertsResource, opts))
}

// Create takes the representation of a localVolumeConvert and creates it.  Returns the server's representation of the localVolumeConvert, and an error, if there is any.
func (c *FakeLocalVolumeConverts) Create(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localvolumeconvertsResource, localVolumeConvert), &v1alpha1.LocalVolumeConvert{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeConvert), err
}

// Update takes the representation of a localVolumeConvert and updates it. Returns the server's representation of the localVolumeConvert, and an error, if there is any.
func (c *FakeLocalVolumeConverts) Update(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localvolumeconvertsResource, localVolumeConvert), &v1alpha1.LocalVolumeConvert{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeConvert), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalVolumeConverts) UpdateStatus(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeConvert, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localvolumeconvertsResource, "status", localVolumeConvert), &v1alpha1.LocalVolumeConvert{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeConvert), err
}

// Delete takes name of the localVolumeConvert and deletes it. Returns an error if one occurs.
func (c *FakeLocalVolumeConverts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localvolumeconvertsResource, name), &v1alpha1.LocalVolumeConvert{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalVolumeConverts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localvolumeconvertsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalVolumeConvertList{})
	return err
}

// Patch applies the patch and returns the patched localVolumeConvert.
func (c *FakeLocalVolumeConverts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeConvert, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localvolumeconvertsResource, name, pt, data, subresources...), &v1alpha1.LocalVolumeConvert{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeConvert), err
}
