// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFaultTickets implements FaultTicketInterface
type FakeFaultTickets struct {
	Fake *FakeHwameistorV1alpha1
}

var faultticketsResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "faulttickets"}

var faultticketsKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "FaultTicket"}

// Get takes name of the faultTicket, and returns the corresponding faultTicket object, and an error if there is any.
func (c *FakeFaultTickets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FaultTicket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(faultticketsResource, name), &v1alpha1.FaultTicket{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultTicket), err
}

// List takes label and field selectors, and returns the list of FaultTickets that match those selectors.
func (c *FakeFaultTickets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FaultTicketList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(faultticketsResource, faultticketsKind, opts), &v1alpha1.FaultTicketList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FaultTicketList{ListMeta: obj.(*v1alpha1.FaultTicketList).ListMeta}
	for _, item := range obj.(*v1alpha1.FaultTicketList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested faultTickets.
func (c *FakeFaultTickets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(faultticketsResource, opts))
}

// Create takes the representation of a faultTicket and creates it.  Returns the server's representation of the faultTicket, and an error, if there is any.
func (c *FakeFaultTickets) Create(ctx context.Context, faultTicket *v1alpha1.FaultTicket, opts v1.CreateOptions) (result *v1alpha1.FaultTicket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(faultticketsResource, faultTicket), &v1alpha1.FaultTicket{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultTicket), err
}

// Update takes the representation of a faultTicket and updates it. Returns the server's representation of the faultTicket, and an error, if there is any.
func (c *FakeFaultTickets) Update(ctx context.Context, faultTicket *v1alpha1.FaultTicket, opts v1.UpdateOptions) (result *v1alpha1.FaultTicket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(faultticketsResource, faultTicket), &v1alpha1.FaultTicket{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultTicket), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFaultTickets) UpdateStatus(ctx context.Context, faultTicket *v1alpha1.FaultTicket, opts v1.UpdateOptions) (*v1alpha1.FaultTicket, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(faultticketsResource, "status", faultTicket), &v1alpha1.FaultTicket{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultTicket), err
}

// Delete takes name of the faultTicket and deletes it. Returns an error if one occurs.
func (c *FakeFaultTickets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(faultticketsResource, name), &v1alpha1.FaultTicket{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFaultTickets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(faultticketsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FaultTicketList{})
	return err
}

// Patch applies the patch and returns the patched faultTicket.
func (c *FakeFaultTickets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FaultTicket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(faultticketsResource, name, pt, data, subresources...), &v1alpha1.FaultTicket{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultTicket), err
}
