// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalDiskVolumes implements LocalDiskVolumeInterface
type FakeLocalDiskVolumes struct {
	Fake *FakeHwameistorV1alpha1
}

var localdiskvolumesResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localdiskvolumes"}

var localdiskvolumesKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalDiskVolume"}

// Get takes name of the localDiskVolume, and returns the corresponding localDiskVolume object, and an error if there is any.
func (c *FakeLocalDiskVolumes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalDiskVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localdiskvolumesResource, name), &v1alpha1.LocalDiskVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskVolume), err
}

// List takes label and field selectors, and returns the list of LocalDiskVolumes that match those selectors.
func (c *FakeLocalDiskVolumes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalDiskVolumeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localdiskvolumesResource, localdiskvolumesKind, opts), &v1alpha1.LocalDiskVolumeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalDiskVolumeList{ListMeta: obj.(*v1alpha1.LocalDiskVolumeList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalDiskVolumeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localDiskVolumes.
func (c *FakeLocalDiskVolumes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localdiskvolumesResource, opts))
}

// Create takes the representation of a localDiskVolume and creates it.  Returns the server's representation of the localDiskVolume, and an error, if there is any.
func (c *FakeLocalDiskVolumes) Create(ctx context.Context, localDiskVolume *v1alpha1.LocalDiskVolume, opts v1.CreateOptions) (result *v1alpha1.LocalDiskVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localdiskvolumesResource, localDiskVolume), &v1alpha1.LocalDiskVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskVolume), err
}

// Update takes the representation of a localDiskVolume and updates it. Returns the server's representation of the localDiskVolume, and an error, if there is any.
func (c *FakeLocalDiskVolumes) Update(ctx context.Context, localDiskVolume *v1alpha1.LocalDiskVolume, opts v1.UpdateOptions) (result *v1alpha1.LocalDiskVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localdiskvolumesResource, localDiskVolume), &v1alpha1.LocalDiskVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskVolume), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalDiskVolumes) UpdateStatus(ctx context.Context, localDiskVolume *v1alpha1.LocalDiskVolume, opts v1.UpdateOptions) (*v1alpha1.LocalDiskVolume, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localdiskvolumesResource, "status", localDiskVolume), &v1alpha1.LocalDiskVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskVolume), err
}

// Delete takes name of the localDiskVolume and deletes it. Returns an error if one occurs.
func (c *FakeLocalDiskVolumes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localdiskvolumesResource, name), &v1alpha1.LocalDiskVolume{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalDiskVolumes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localdiskvolumesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalDiskVolumeList{})
	return err
}

// Patch applies the patch and returns the patched localDiskVolume.
func (c *FakeLocalDiskVolumes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalDiskVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localdiskvolumesResource, name, pt, data, subresources...), &v1alpha1.LocalDiskVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskVolume), err
}
