// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalVolumeReplicas implements LocalVolumeReplicaInterface
type FakeLocalVolumeReplicas struct {
	Fake *FakeHwameistorV1alpha1
}

var localvolumereplicasResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localvolumereplicas"}

var localvolumereplicasKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalVolumeReplica"}

// Get takes name of the localVolumeReplica, and returns the corresponding localVolumeReplica object, and an error if there is any.
func (c *FakeLocalVolumeReplicas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localvolumereplicasResource, name), &v1alpha1.LocalVolumeReplica{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeReplica), err
}

// List takes label and field selectors, and returns the list of LocalVolumeReplicas that match those selectors.
func (c *FakeLocalVolumeReplicas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeReplicaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localvolumereplicasResource, localvolumereplicasKind, opts), &v1alpha1.LocalVolumeReplicaList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalVolumeReplicaList{ListMeta: obj.(*v1alpha1.LocalVolumeReplicaList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalVolumeReplicaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localVolumeReplicas.
func (c *FakeLocalVolumeReplicas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localvolumereplicasResource, opts))
}

// Create takes the representation of a localVolumeReplica and creates it.  Returns the server's representation of the localVolumeReplica, and an error, if there is any.
func (c *FakeLocalVolumeReplicas) Create(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localvolumereplicasResource, localVolumeReplica), &v1alpha1.LocalVolumeReplica{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeReplica), err
}

// Update takes the representation of a localVolumeReplica and updates it. Returns the server's representation of the localVolumeReplica, and an error, if there is any.
func (c *FakeLocalVolumeReplicas) Update(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localvolumereplicasResource, localVolumeReplica), &v1alpha1.LocalVolumeReplica{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeReplica), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalVolumeReplicas) UpdateStatus(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeReplica, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localvolumereplicasResource, "status", localVolumeReplica), &v1alpha1.LocalVolumeReplica{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeReplica), err
}

// Delete takes name of the localVolumeReplica and deletes it. Returns an error if one occurs.
func (c *FakeLocalVolumeReplicas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localvolumereplicasResource, name), &v1alpha1.LocalVolumeReplica{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalVolumeReplicas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localvolumereplicasResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalVolumeReplicaList{})
	return err
}

// Patch applies the patch and returns the patched localVolumeReplica.
func (c *FakeLocalVolumeReplicas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeReplica, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localvolumereplicasResource, name, pt, data, subresources...), &v1alpha1.LocalVolumeReplica{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeReplica), err
}
