// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/client/clientset/versioned/typed/hwameistor/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeHwameistorV1alpha1 struct {
	*testing.Fake
}

func (c *FakeHwameistorV1alpha1) Events() v1alpha1.EventInterface {
	return &FakeEvents{c}
}

func (c *FakeHwameistorV1alpha1) LocalDisks() v1alpha1.LocalDiskInterface {
	return &FakeLocalDisks{c}
}

func (c *FakeHwameistorV1alpha1) LocalDiskActions() v1alpha1.LocalDiskActionInterface {
	return &FakeLocalDiskActions{c}
}

func (c *FakeHwameistorV1alpha1) LocalDiskClaims() v1alpha1.LocalDiskClaimInterface {
	return &FakeLocalDiskClaims{c}
}

func (c *FakeHwameistorV1alpha1) LocalDiskNodes() v1alpha1.LocalDiskNodeInterface {
	return &FakeLocalDiskNodes{c}
}

func (c *FakeHwameistorV1alpha1) LocalDiskVolumes() v1alpha1.LocalDiskVolumeInterface {
	return &FakeLocalDiskVolumes{c}
}

func (c *FakeHwameistorV1alpha1) LocalStorageNodes() v1alpha1.LocalStorageNodeInterface {
	return &FakeLocalStorageNodes{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumes() v1alpha1.LocalVolumeInterface {
	return &FakeLocalVolumes{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeConverts() v1alpha1.LocalVolumeConvertInterface {
	return &FakeLocalVolumeConverts{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeExpands() v1alpha1.LocalVolumeExpandInterface {
	return &FakeLocalVolumeExpands{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeGroups() v1alpha1.LocalVolumeGroupInterface {
	return &FakeLocalVolumeGroups{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeMigrates() v1alpha1.LocalVolumeMigrateInterface {
	return &FakeLocalVolumeMigrates{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeReplicas() v1alpha1.LocalVolumeReplicaInterface {
	return &FakeLocalVolumeReplicas{c}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeSnapshots(namespace string) v1alpha1.LocalVolumeSnapshotInterface {
	return &FakeLocalVolumeSnapshots{c, namespace}
}

func (c *FakeHwameistorV1alpha1) LocalVolumeSnapshotRestores(namespace string) v1alpha1.LocalVolumeSnapshotRestoreInterface {
	return &FakeLocalVolumeSnapshotRestores{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeHwameistorV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
