// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalDiskActions implements LocalDiskActionInterface
type FakeLocalDiskActions struct {
	Fake *FakeHwameistorV1alpha1
}

var localdiskactionsResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localdiskactions"}

var localdiskactionsKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalDiskAction"}

// Get takes name of the localDiskAction, and returns the corresponding localDiskAction object, and an error if there is any.
func (c *FakeLocalDiskActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalDiskAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localdiskactionsResource, name), &v1alpha1.LocalDiskAction{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskAction), err
}

// List takes label and field selectors, and returns the list of LocalDiskActions that match those selectors.
func (c *FakeLocalDiskActions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalDiskActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localdiskactionsResource, localdiskactionsKind, opts), &v1alpha1.LocalDiskActionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalDiskActionList{ListMeta: obj.(*v1alpha1.LocalDiskActionList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalDiskActionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localDiskActions.
func (c *FakeLocalDiskActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localdiskactionsResource, opts))
}

// Create takes the representation of a localDiskAction and creates it.  Returns the server's representation of the localDiskAction, and an error, if there is any.
func (c *FakeLocalDiskActions) Create(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.CreateOptions) (result *v1alpha1.LocalDiskAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localdiskactionsResource, localDiskAction), &v1alpha1.LocalDiskAction{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskAction), err
}

// Update takes the representation of a localDiskAction and updates it. Returns the server's representation of the localDiskAction, and an error, if there is any.
func (c *FakeLocalDiskActions) Update(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.UpdateOptions) (result *v1alpha1.LocalDiskAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localdiskactionsResource, localDiskAction), &v1alpha1.LocalDiskAction{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskAction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalDiskActions) UpdateStatus(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.UpdateOptions) (*v1alpha1.LocalDiskAction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localdiskactionsResource, "status", localDiskAction), &v1alpha1.LocalDiskAction{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskAction), err
}

// Delete takes name of the localDiskAction and deletes it. Returns an error if one occurs.
func (c *FakeLocalDiskActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localdiskactionsResource, name), &v1alpha1.LocalDiskAction{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalDiskActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localdiskactionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalDiskActionList{})
	return err
}

// Patch applies the patch and returns the patched localDiskAction.
func (c *FakeLocalDiskActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalDiskAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localdiskactionsResource, name, pt, data, subresources...), &v1alpha1.LocalDiskAction{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalDiskAction), err
}
