// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalVolumeGroups implements LocalVolumeGroupInterface
type FakeLocalVolumeGroups struct {
	Fake *FakeHwameistorV1alpha1
}

var localvolumegroupsResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localvolumegroups"}

var localvolumegroupsKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalVolumeGroup"}

// Get takes name of the localVolumeGroup, and returns the corresponding localVolumeGroup object, and an error if there is any.
func (c *FakeLocalVolumeGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localvolumegroupsResource, name), &v1alpha1.LocalVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeGroup), err
}

// List takes label and field selectors, and returns the list of LocalVolumeGroups that match those selectors.
func (c *FakeLocalVolumeGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localvolumegroupsResource, localvolumegroupsKind, opts), &v1alpha1.LocalVolumeGroupList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalVolumeGroupList{ListMeta: obj.(*v1alpha1.LocalVolumeGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalVolumeGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localVolumeGroups.
func (c *FakeLocalVolumeGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localvolumegroupsResource, opts))
}

// Create takes the representation of a localVolumeGroup and creates it.  Returns the server's representation of the localVolumeGroup, and an error, if there is any.
func (c *FakeLocalVolumeGroups) Create(ctx context.Context, localVolumeGroup *v1alpha1.LocalVolumeGroup, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localvolumegroupsResource, localVolumeGroup), &v1alpha1.LocalVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeGroup), err
}

// Update takes the representation of a localVolumeGroup and updates it. Returns the server's representation of the localVolumeGroup, and an error, if there is any.
func (c *FakeLocalVolumeGroups) Update(ctx context.Context, localVolumeGroup *v1alpha1.LocalVolumeGroup, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localvolumegroupsResource, localVolumeGroup), &v1alpha1.LocalVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalVolumeGroups) UpdateStatus(ctx context.Context, localVolumeGroup *v1alpha1.LocalVolumeGroup, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localvolumegroupsResource, "status", localVolumeGroup), &v1alpha1.LocalVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeGroup), err
}

// Delete takes name of the localVolumeGroup and deletes it. Returns an error if one occurs.
func (c *FakeLocalVolumeGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localvolumegroupsResource, name), &v1alpha1.LocalVolumeGroup{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalVolumeGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localvolumegroupsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalVolumeGroupList{})
	return err
}

// Patch applies the patch and returns the patched localVolumeGroup.
func (c *FakeLocalVolumeGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localvolumegroupsResource, name, pt, data, subresources...), &v1alpha1.LocalVolumeGroup{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeGroup), err
}
