// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalVolumeMigrates implements LocalVolumeMigrateInterface
type FakeLocalVolumeMigrates struct {
	Fake *FakeHwameistorV1alpha1
}

var localvolumemigratesResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localvolumemigrates"}

var localvolumemigratesKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalVolumeMigrate"}

// Get takes name of the localVolumeMigrate, and returns the corresponding localVolumeMigrate object, and an error if there is any.
func (c *FakeLocalVolumeMigrates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localvolumemigratesResource, name), &v1alpha1.LocalVolumeMigrate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeMigrate), err
}

// List takes label and field selectors, and returns the list of LocalVolumeMigrates that match those selectors.
func (c *FakeLocalVolumeMigrates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeMigrateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localvolumemigratesResource, localvolumemigratesKind, opts), &v1alpha1.LocalVolumeMigrateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalVolumeMigrateList{ListMeta: obj.(*v1alpha1.LocalVolumeMigrateList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalVolumeMigrateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localVolumeMigrates.
func (c *FakeLocalVolumeMigrates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localvolumemigratesResource, opts))
}

// Create takes the representation of a localVolumeMigrate and creates it.  Returns the server's representation of the localVolumeMigrate, and an error, if there is any.
func (c *FakeLocalVolumeMigrates) Create(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localvolumemigratesResource, localVolumeMigrate), &v1alpha1.LocalVolumeMigrate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeMigrate), err
}

// Update takes the representation of a localVolumeMigrate and updates it. Returns the server's representation of the localVolumeMigrate, and an error, if there is any.
func (c *FakeLocalVolumeMigrates) Update(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localvolumemigratesResource, localVolumeMigrate), &v1alpha1.LocalVolumeMigrate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeMigrate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalVolumeMigrates) UpdateStatus(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeMigrate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localvolumemigratesResource, "status", localVolumeMigrate), &v1alpha1.LocalVolumeMigrate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeMigrate), err
}

// Delete takes name of the localVolumeMigrate and deletes it. Returns an error if one occurs.
func (c *FakeLocalVolumeMigrates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localvolumemigratesResource, name), &v1alpha1.LocalVolumeMigrate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalVolumeMigrates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localvolumemigratesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalVolumeMigrateList{})
	return err
}

// Patch applies the patch and returns the patched localVolumeMigrate.
func (c *FakeLocalVolumeMigrates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeMigrate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localvolumemigratesResource, name, pt, data, subresources...), &v1alpha1.LocalVolumeMigrate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolumeMigrate), err
}
