// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLocalVolumes implements LocalVolumeInterface
type FakeLocalVolumes struct {
	Fake *FakeHwameistorV1alpha1
}

var localvolumesResource = schema.GroupVersionResource{Group: "hwameistor.io", Version: "v1alpha1", Resource: "localvolumes"}

var localvolumesKind = schema.GroupVersionKind{Group: "hwameistor.io", Version: "v1alpha1", Kind: "LocalVolume"}

// Get takes name of the localVolume, and returns the corresponding localVolume object, and an error if there is any.
func (c *FakeLocalVolumes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(localvolumesResource, name), &v1alpha1.LocalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolume), err
}

// List takes label and field selectors, and returns the list of LocalVolumes that match those selectors.
func (c *FakeLocalVolumes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(localvolumesResource, localvolumesKind, opts), &v1alpha1.LocalVolumeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LocalVolumeList{ListMeta: obj.(*v1alpha1.LocalVolumeList).ListMeta}
	for _, item := range obj.(*v1alpha1.LocalVolumeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested localVolumes.
func (c *FakeLocalVolumes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(localvolumesResource, opts))
}

// Create takes the representation of a localVolume and creates it.  Returns the server's representation of the localVolume, and an error, if there is any.
func (c *FakeLocalVolumes) Create(ctx context.Context, localVolume *v1alpha1.LocalVolume, opts v1.CreateOptions) (result *v1alpha1.LocalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(localvolumesResource, localVolume), &v1alpha1.LocalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolume), err
}

// Update takes the representation of a localVolume and updates it. Returns the server's representation of the localVolume, and an error, if there is any.
func (c *FakeLocalVolumes) Update(ctx context.Context, localVolume *v1alpha1.LocalVolume, opts v1.UpdateOptions) (result *v1alpha1.LocalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(localvolumesResource, localVolume), &v1alpha1.LocalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolume), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLocalVolumes) UpdateStatus(ctx context.Context, localVolume *v1alpha1.LocalVolume, opts v1.UpdateOptions) (*v1alpha1.LocalVolume, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(localvolumesResource, "status", localVolume), &v1alpha1.LocalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolume), err
}

// Delete takes name of the localVolume and deletes it. Returns an error if one occurs.
func (c *FakeLocalVolumes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(localvolumesResource, name), &v1alpha1.LocalVolume{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLocalVolumes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(localvolumesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LocalVolumeList{})
	return err
}

// Patch applies the patch and returns the patched localVolume.
func (c *FakeLocalVolumes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolume, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(localvolumesResource, name, pt, data, subresources...), &v1alpha1.LocalVolume{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LocalVolume), err
}
