# Claim nodes disks
{{-  range .Values.storageNodes }}
{{- $name :=  .  }}
apiVersion: hwameistor.io/v1alpha1
kind: LocalDiskClaim
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-failed
  name: {{ $name }}
spec:
  # nodeName is the node where disk is attached
  # If nodeName contains ".",please replace it with "-".
  # The field value should be consistent with the nodeName in localdisk
  nodeName: {{ . }}
  description:
    diskType: {{ $.Values.storageClass.diskType }}
---
{{- end}}
