{{- if .Values.storageClass.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageClass.kubernetes.io/is-default-class: {{ .Values.storageClass.default | quote }}
  name: hwameistor-storage-lvm-{{ .Values.storageClass.diskType | lower}}
provisioner: lvm.hwameistor.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
parameters:
  replicaNumber: {{ .Values.storageClass.replicaNumber | quote}}
  poolClass: {{ .Values.storageClass.diskType | quote}}
  poolType: "REGULAR"
  volumeKind: "LVM"
  striped: "true"
  convertible: {{ .Values.storageClass.convertible | quote}}
  csi.storage.k8s.io/fstype: {{ .Values.storageClass.fsType | quote}}
{{- end }}
