// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type EventExpansion interface{}

type LocalDiskExpansion interface{}

type LocalDiskActionExpansion interface{}

type LocalDiskClaimExpansion interface{}

type LocalDiskNodeExpansion interface{}

type LocalDiskVolumeExpansion interface{}

type LocalStorageNodeExpansion interface{}

type LocalVolumeExpansion interface{}

type LocalVolumeConvertExpansion interface{}

type LocalVolumeExpandExpansion interface{}

type LocalVolumeGroupExpansion interface{}

type LocalVolumeMigrateExpansion interface{}

type LocalVolumeReplicaExpansion interface{}

type LocalVolumeSnapshotExpansion interface{}

type LocalVolumeSnapshotRestoreExpansion interface{}
