// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/hwameistor/hwameistor/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalVolumeConvertsGetter has a method to return a LocalVolumeConvertInterface.
// A group's client should implement this interface.
type LocalVolumeConvertsGetter interface {
	LocalVolumeConverts() LocalVolumeConvertInterface
}

// LocalVolumeConvertInterface has methods to work with LocalVolumeConvert resources.
type LocalVolumeConvertInterface interface {
	Create(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.CreateOptions) (*v1alpha1.LocalVolumeConvert, error)
	Update(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeConvert, error)
	UpdateStatus(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeConvert, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LocalVolumeConvert, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LocalVolumeConvertList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeConvert, err error)
	LocalVolumeConvertExpansion
}

// localVolumeConverts implements LocalVolumeConvertInterface
type localVolumeConverts struct {
	client rest.Interface
}

// newLocalVolumeConverts returns a LocalVolumeConverts
func newLocalVolumeConverts(c *HwameistorV1alpha1Client) *localVolumeConverts {
	return &localVolumeConverts{
		client: c.RESTClient(),
	}
}

// Get takes name of the localVolumeConvert, and returns the corresponding localVolumeConvert object, and an error if there is any.
func (c *localVolumeConverts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	result = &v1alpha1.LocalVolumeConvert{}
	err = c.client.Get().
		Resource("localvolumeconverts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalVolumeConverts that match those selectors.
func (c *localVolumeConverts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeConvertList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LocalVolumeConvertList{}
	err = c.client.Get().
		Resource("localvolumeconverts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localVolumeConverts.
func (c *localVolumeConverts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localvolumeconverts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localVolumeConvert and creates it.  Returns the server's representation of the localVolumeConvert, and an error, if there is any.
func (c *localVolumeConverts) Create(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	result = &v1alpha1.LocalVolumeConvert{}
	err = c.client.Post().
		Resource("localvolumeconverts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeConvert).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localVolumeConvert and updates it. Returns the server's representation of the localVolumeConvert, and an error, if there is any.
func (c *localVolumeConverts) Update(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	result = &v1alpha1.LocalVolumeConvert{}
	err = c.client.Put().
		Resource("localvolumeconverts").
		Name(localVolumeConvert.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeConvert).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localVolumeConverts) UpdateStatus(ctx context.Context, localVolumeConvert *v1alpha1.LocalVolumeConvert, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeConvert, err error) {
	result = &v1alpha1.LocalVolumeConvert{}
	err = c.client.Put().
		Resource("localvolumeconverts").
		Name(localVolumeConvert.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeConvert).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localVolumeConvert and deletes it. Returns an error if one occurs.
func (c *localVolumeConverts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localvolumeconverts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localVolumeConverts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localvolumeconverts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localVolumeConvert.
func (c *localVolumeConverts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeConvert, err error) {
	result = &v1alpha1.LocalVolumeConvert{}
	err = c.client.Patch(pt).
		Resource("localvolumeconverts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
