// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/hwameistor/hwameistor/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalVolumeMigratesGetter has a method to return a LocalVolumeMigrateInterface.
// A group's client should implement this interface.
type LocalVolumeMigratesGetter interface {
	LocalVolumeMigrates() LocalVolumeMigrateInterface
}

// LocalVolumeMigrateInterface has methods to work with LocalVolumeMigrate resources.
type LocalVolumeMigrateInterface interface {
	Create(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.CreateOptions) (*v1alpha1.LocalVolumeMigrate, error)
	Update(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeMigrate, error)
	UpdateStatus(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeMigrate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LocalVolumeMigrate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LocalVolumeMigrateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeMigrate, err error)
	LocalVolumeMigrateExpansion
}

// localVolumeMigrates implements LocalVolumeMigrateInterface
type localVolumeMigrates struct {
	client rest.Interface
}

// newLocalVolumeMigrates returns a LocalVolumeMigrates
func newLocalVolumeMigrates(c *HwameistorV1alpha1Client) *localVolumeMigrates {
	return &localVolumeMigrates{
		client: c.RESTClient(),
	}
}

// Get takes name of the localVolumeMigrate, and returns the corresponding localVolumeMigrate object, and an error if there is any.
func (c *localVolumeMigrates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	result = &v1alpha1.LocalVolumeMigrate{}
	err = c.client.Get().
		Resource("localvolumemigrates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalVolumeMigrates that match those selectors.
func (c *localVolumeMigrates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeMigrateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LocalVolumeMigrateList{}
	err = c.client.Get().
		Resource("localvolumemigrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localVolumeMigrates.
func (c *localVolumeMigrates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localvolumemigrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localVolumeMigrate and creates it.  Returns the server's representation of the localVolumeMigrate, and an error, if there is any.
func (c *localVolumeMigrates) Create(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	result = &v1alpha1.LocalVolumeMigrate{}
	err = c.client.Post().
		Resource("localvolumemigrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeMigrate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localVolumeMigrate and updates it. Returns the server's representation of the localVolumeMigrate, and an error, if there is any.
func (c *localVolumeMigrates) Update(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	result = &v1alpha1.LocalVolumeMigrate{}
	err = c.client.Put().
		Resource("localvolumemigrates").
		Name(localVolumeMigrate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeMigrate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localVolumeMigrates) UpdateStatus(ctx context.Context, localVolumeMigrate *v1alpha1.LocalVolumeMigrate, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeMigrate, err error) {
	result = &v1alpha1.LocalVolumeMigrate{}
	err = c.client.Put().
		Resource("localvolumemigrates").
		Name(localVolumeMigrate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeMigrate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localVolumeMigrate and deletes it. Returns an error if one occurs.
func (c *localVolumeMigrates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localvolumemigrates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localVolumeMigrates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localvolumemigrates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localVolumeMigrate.
func (c *localVolumeMigrates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeMigrate, err error) {
	result = &v1alpha1.LocalVolumeMigrate{}
	err = c.client.Patch(pt).
		Resource("localvolumemigrates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
