/*
Copyright 2022 Contributors to The HwameiStor project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/hwameistor/local-storage/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/local-storage/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalVolumeGroupMigratesGetter has a method to return a LocalVolumeGroupMigrateInterface.
// A group's client should implement this interface.
type LocalVolumeGroupMigratesGetter interface {
	LocalVolumeGroupMigrates() LocalVolumeGroupMigrateInterface
}

// LocalVolumeGroupMigrateInterface has methods to work with LocalVolumeGroupMigrate resources.
type LocalVolumeGroupMigrateInterface interface {
	Create(ctx context.Context, localVolumeGroupMigrate *v1alpha1.LocalVolumeGroupMigrate, opts v1.CreateOptions) (*v1alpha1.LocalVolumeGroupMigrate, error)
	Update(ctx context.Context, localVolumeGroupMigrate *v1alpha1.LocalVolumeGroupMigrate, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeGroupMigrate, error)
	UpdateStatus(ctx context.Context, localVolumeGroupMigrate *v1alpha1.LocalVolumeGroupMigrate, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeGroupMigrate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LocalVolumeGroupMigrate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LocalVolumeGroupMigrateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeGroupMigrate, err error)
	LocalVolumeGroupMigrateExpansion
}

// localVolumeGroupMigrates implements LocalVolumeGroupMigrateInterface
type localVolumeGroupMigrates struct {
	client rest.Interface
}

// newLocalVolumeGroupMigrates returns a LocalVolumeGroupMigrates
func newLocalVolumeGroupMigrates(c *HwameistorV1alpha1Client) *localVolumeGroupMigrates {
	return &localVolumeGroupMigrates{
		client: c.RESTClient(),
	}
}

// Get takes name of the localVolumeGroupMigrate, and returns the corresponding localVolumeGroupMigrate object, and an error if there is any.
func (c *localVolumeGroupMigrates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeGroupMigrate, err error) {
	result = &v1alpha1.LocalVolumeGroupMigrate{}
	err = c.client.Get().
		Resource("localvolumegroupmigrates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalVolumeGroupMigrates that match those selectors.
func (c *localVolumeGroupMigrates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeGroupMigrateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LocalVolumeGroupMigrateList{}
	err = c.client.Get().
		Resource("localvolumegroupmigrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localVolumeGroupMigrates.
func (c *localVolumeGroupMigrates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localvolumegroupmigrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localVolumeGroupMigrate and creates it.  Returns the server's representation of the localVolumeGroupMigrate, and an error, if there is any.
func (c *localVolumeGroupMigrates) Create(ctx context.Context, localVolumeGroupMigrate *v1alpha1.LocalVolumeGroupMigrate, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeGroupMigrate, err error) {
	result = &v1alpha1.LocalVolumeGroupMigrate{}
	err = c.client.Post().
		Resource("localvolumegroupmigrates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeGroupMigrate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localVolumeGroupMigrate and updates it. Returns the server's representation of the localVolumeGroupMigrate, and an error, if there is any.
func (c *localVolumeGroupMigrates) Update(ctx context.Context, localVolumeGroupMigrate *v1alpha1.LocalVolumeGroupMigrate, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeGroupMigrate, err error) {
	result = &v1alpha1.LocalVolumeGroupMigrate{}
	err = c.client.Put().
		Resource("localvolumegroupmigrates").
		Name(localVolumeGroupMigrate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeGroupMigrate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localVolumeGroupMigrates) UpdateStatus(ctx context.Context, localVolumeGroupMigrate *v1alpha1.LocalVolumeGroupMigrate, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeGroupMigrate, err error) {
	result = &v1alpha1.LocalVolumeGroupMigrate{}
	err = c.client.Put().
		Resource("localvolumegroupmigrates").
		Name(localVolumeGroupMigrate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeGroupMigrate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localVolumeGroupMigrate and deletes it. Returns an error if one occurs.
func (c *localVolumeGroupMigrates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localvolumegroupmigrates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localVolumeGroupMigrates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localvolumegroupmigrates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localVolumeGroupMigrate.
func (c *localVolumeGroupMigrates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeGroupMigrate, err error) {
	result = &v1alpha1.LocalVolumeGroupMigrate{}
	err = c.client.Patch(pt).
		Resource("localvolumegroupmigrates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
