// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/hwameistor/hwameistor/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalDiskActionsGetter has a method to return a LocalDiskActionInterface.
// A group's client should implement this interface.
type LocalDiskActionsGetter interface {
	LocalDiskActions() LocalDiskActionInterface
}

// LocalDiskActionInterface has methods to work with LocalDiskAction resources.
type LocalDiskActionInterface interface {
	Create(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.CreateOptions) (*v1alpha1.LocalDiskAction, error)
	Update(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.UpdateOptions) (*v1alpha1.LocalDiskAction, error)
	UpdateStatus(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.UpdateOptions) (*v1alpha1.LocalDiskAction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LocalDiskAction, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LocalDiskActionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalDiskAction, err error)
	LocalDiskActionExpansion
}

// localDiskActions implements LocalDiskActionInterface
type localDiskActions struct {
	client rest.Interface
}

// newLocalDiskActions returns a LocalDiskActions
func newLocalDiskActions(c *HwameistorV1alpha1Client) *localDiskActions {
	return &localDiskActions{
		client: c.RESTClient(),
	}
}

// Get takes name of the localDiskAction, and returns the corresponding localDiskAction object, and an error if there is any.
func (c *localDiskActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalDiskAction, err error) {
	result = &v1alpha1.LocalDiskAction{}
	err = c.client.Get().
		Resource("localdiskactions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalDiskActions that match those selectors.
func (c *localDiskActions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalDiskActionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LocalDiskActionList{}
	err = c.client.Get().
		Resource("localdiskactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localDiskActions.
func (c *localDiskActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localdiskactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localDiskAction and creates it.  Returns the server's representation of the localDiskAction, and an error, if there is any.
func (c *localDiskActions) Create(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.CreateOptions) (result *v1alpha1.LocalDiskAction, err error) {
	result = &v1alpha1.LocalDiskAction{}
	err = c.client.Post().
		Resource("localdiskactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localDiskAction).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localDiskAction and updates it. Returns the server's representation of the localDiskAction, and an error, if there is any.
func (c *localDiskActions) Update(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.UpdateOptions) (result *v1alpha1.LocalDiskAction, err error) {
	result = &v1alpha1.LocalDiskAction{}
	err = c.client.Put().
		Resource("localdiskactions").
		Name(localDiskAction.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localDiskAction).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localDiskActions) UpdateStatus(ctx context.Context, localDiskAction *v1alpha1.LocalDiskAction, opts v1.UpdateOptions) (result *v1alpha1.LocalDiskAction, err error) {
	result = &v1alpha1.LocalDiskAction{}
	err = c.client.Put().
		Resource("localdiskactions").
		Name(localDiskAction.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localDiskAction).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localDiskAction and deletes it. Returns an error if one occurs.
func (c *localDiskActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localdiskactions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localDiskActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localdiskactions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localDiskAction.
func (c *localDiskActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalDiskAction, err error) {
	result = &v1alpha1.LocalDiskAction{}
	err = c.client.Patch(pt).
		Resource("localdiskactions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
