// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/hwameistor/hwameistor/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalVolumeReplicasGetter has a method to return a LocalVolumeReplicaInterface.
// A group's client should implement this interface.
type LocalVolumeReplicasGetter interface {
	LocalVolumeReplicas() LocalVolumeReplicaInterface
}

// LocalVolumeReplicaInterface has methods to work with LocalVolumeReplica resources.
type LocalVolumeReplicaInterface interface {
	Create(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.CreateOptions) (*v1alpha1.LocalVolumeReplica, error)
	Update(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeReplica, error)
	UpdateStatus(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.UpdateOptions) (*v1alpha1.LocalVolumeReplica, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LocalVolumeReplica, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LocalVolumeReplicaList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeReplica, err error)
	LocalVolumeReplicaExpansion
}

// localVolumeReplicas implements LocalVolumeReplicaInterface
type localVolumeReplicas struct {
	client rest.Interface
}

// newLocalVolumeReplicas returns a LocalVolumeReplicas
func newLocalVolumeReplicas(c *HwameistorV1alpha1Client) *localVolumeReplicas {
	return &localVolumeReplicas{
		client: c.RESTClient(),
	}
}

// Get takes name of the localVolumeReplica, and returns the corresponding localVolumeReplica object, and an error if there is any.
func (c *localVolumeReplicas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	result = &v1alpha1.LocalVolumeReplica{}
	err = c.client.Get().
		Resource("localvolumereplicas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalVolumeReplicas that match those selectors.
func (c *localVolumeReplicas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalVolumeReplicaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LocalVolumeReplicaList{}
	err = c.client.Get().
		Resource("localvolumereplicas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localVolumeReplicas.
func (c *localVolumeReplicas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localvolumereplicas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localVolumeReplica and creates it.  Returns the server's representation of the localVolumeReplica, and an error, if there is any.
func (c *localVolumeReplicas) Create(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.CreateOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	result = &v1alpha1.LocalVolumeReplica{}
	err = c.client.Post().
		Resource("localvolumereplicas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeReplica).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localVolumeReplica and updates it. Returns the server's representation of the localVolumeReplica, and an error, if there is any.
func (c *localVolumeReplicas) Update(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	result = &v1alpha1.LocalVolumeReplica{}
	err = c.client.Put().
		Resource("localvolumereplicas").
		Name(localVolumeReplica.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeReplica).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localVolumeReplicas) UpdateStatus(ctx context.Context, localVolumeReplica *v1alpha1.LocalVolumeReplica, opts v1.UpdateOptions) (result *v1alpha1.LocalVolumeReplica, err error) {
	result = &v1alpha1.LocalVolumeReplica{}
	err = c.client.Put().
		Resource("localvolumereplicas").
		Name(localVolumeReplica.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localVolumeReplica).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localVolumeReplica and deletes it. Returns an error if one occurs.
func (c *localVolumeReplicas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localvolumereplicas").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localVolumeReplicas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localvolumereplicas").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localVolumeReplica.
func (c *localVolumeReplicas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalVolumeReplica, err error) {
	result = &v1alpha1.LocalVolumeReplica{}
	err = c.client.Patch(pt).
		Resource("localvolumereplicas").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
