apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localvolumereplicasnapshots.hwameistor.io
spec:
  group: hwameistor.io
  names:
    kind: LocalVolumeReplicaSnapshot
    listKind: LocalVolumeReplicaSnapshotList
    plural: localvolumereplicasnapshots
    shortNames:
    - lvrs
    singular: localvolumereplicasnapshot
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Allocated capacity of the snapshot
      jsonPath: .status.allocatedCapacityBytes
      name: Capacity
      type: integer
    - description: Node where snapshot is located
      jsonPath: .spec.nodeName
      name: NodeName
      type: string
    - description: Name of the snapshot's source volume
      jsonPath: .spec.sourceVolume
      name: SourceVolume
      type: string
    - description: State of the snapshot
      jsonPath: .status.state
      name: State
      type: string
    - description: if the snapshot is merging
      jsonPath: .status.attr.merging
      name: Merging
      type: string
    - description: if the snapshot is invalid
      jsonPath: .status.attr.invalid
      name: Invalid
      type: string
    - jsonPath: .status.creationTime
      name: Age
      type: date
    - description: Name of the snapshot's source volume replica
      jsonPath: .spec.sourceVolumeReplica
      name: SourceVolumeReplica
      priority: 1
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: LocalVolumeReplicaSnapshot is the Schema for the localvolumereplicasnapshots
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: LocalVolumeReplicaSnapshotSpec represents the actual localvolume
              snapshot object in lvm
            properties:
              delete:
                default: false
                description: Delete this snapshot if it is true
                type: boolean
              nodeName:
                description: NodeName specifies which node the snapshot will be placed
                type: string
              poolName:
                description: PoolName specifies which volume group the snapshot and
                  source volume is placed valid options are LocalStorage_PoolHDD,
                  LocalStorage_PoolSSD, LocalStorage_PoolNVMe
                enum:
                - LocalStorage_PoolHDD
                - LocalStorage_PoolSSD
                - LocalStorage_PoolNVMe
                type: string
              requiredCapacityBytes:
                description: RequiredCapacityBytes specifies the space reserved for
                  the snapshot
                format: int64
                minimum: 4194304
                type: integer
              sourceVolume:
                description: SourceVolume specifies the source volume name of the
                  snapshot
                type: string
              sourceVolumeReplica:
                description: SourceVolume specifies the source volume replica name
                  of the snapshot
                type: string
              volumeSnapshotName:
                description: VolumeSnapshotName represents the name of volume snapshot
                type: string
            required:
            - nodeName
            - poolName
            - requiredCapacityBytes
            - sourceVolume
            - sourceVolumeReplica
            - volumeSnapshotName
            type: object
          status:
            description: LocalVolumeReplicaSnapshotStatus defines the observed state
              of LocalVolumeReplicaSnapshot
            properties:
              allocatedCapacityBytes:
                description: AllocatedCapacityBytes is the real allocated capacity
                  in bytes
                format: int64
                type: integer
              attr:
                description: Attribute indicates attr on snapshot
                properties:
                  invalid:
                    description: Invalid set true if snapshot is expiration
                    type: boolean
                  merging:
                    description: Merging set true if snapshot is merging now
                    type: boolean
                type: object
              conditions:
                description: Conditions records the information of the volume replica
                  snapshot
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    type FooStatus struct{     // Represents the observations of a
                    foo's current state.     // Known .status.conditions.type are:
                    \"Available\", \"Progressing\", and \"Degraded\"     // +patchMergeKey=type
                    \    // +patchStrategy=merge     // +listType=map     // +listMapKey=type
                    \    Conditions []metav1.Condition `json:\"conditions,omitempty\"
                    patchStrategy:\"merge\" patchMergeKey:\"type\" protobuf:\"bytes,1,rep,name=conditions\"`
                    \n     // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              creationTime:
                description: CreationTime is the host real snapshot creation time
                format: date-time
                type: string
              reason:
                description: Message error message to describe some states
                type: string
              state:
                description: State is the phase of volume replica, e.g. Creating,
                  Ready, NotReady, ToBeDeleted, Deleted
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
