apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s1
resources:
  - namespace.yaml
  - tenant-config.yaml
  - tenant-minio-creds-secret_deprecated.yaml
  - storage-user.yaml
  - tenant.yaml
