{
 "title": "HwameiStor Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Storage Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Summary",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hwameistor_localstoragenode_status) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(hwameistor_localstoragenode_status{status=\"Ready\"}) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(hwameistor_localstoragenode_status) - sum(hwameistor_localstoragenode_status{status=\"Ready\"}) or vector(0)",
     "legendFormat": "Not Ready"
    }
   ]
  },
  {
   "title": "Nodes Storage Usage",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Total\"}",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Used\"}",
     "legendFormat": "Allocated Capacity"
    }
   ]
  },
  {
   "title": "Node Storage Usage Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Total\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Used\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "hwameistor_localstoragenode_capacity{kind=\"Free\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "hwameistor_localstoragenode_volumecount{kind=\"Total\"}",
     "legendFormat": "volTotal"
    },
    {
     "expr": "hwameistor_localstoragenode_volumecount{kind=\"Used\"}",
     "legendFormat": "volUsed"
    },
    {
     "expr": "hwameistor_localstoragenode_volumecount{kind=\"Free\"}",
     "legendFormat": "volFree"
    },
    {
     "expr": "hwameistor_localstoragenode_status",
     "legendFormat": "Status"
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Volumes Status Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hwameistor_localvolume_status) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(hwameistor_localvolume_status{status=\"Ready\"}) or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(hwameistor_localvolume_status) - sum(hwameistor_localvolume_status{status=\"Ready\"}) or vector(0)",
     "legendFormat": "Not Ready"
    }
   ]
  },
  {
   "title": "Volumes Type Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hwameistor_localvolume_status{type=\"HA\"}) or vector(0)",
     "legendFormat": "HA"
    },
    {
     "expr": "count(hwameistor_localvolume_status{type=\"NonHA\"}) or vector(0)",
     "legendFormat": "non-HA"
    },
    {
     "expr": "count(hwameistor_localvolume_status{type=\"Convertible\"}) or vector(0)",
     "legendFormat": "Convertible"
    },
    {
     "expr": "count(hwameistor_localvolume_status{type=\"Disk\"}) or vector(0)",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Volumes Details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hwameistor_localvolumereplica_status",
     "legendFormat": "Auto"
    },
    {
     "expr": "hwameistor_localvolume_capacity{kind=\"Allocated\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hwameistor_localvolume_capacity{kind=\"Used\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Disks Status Overview",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hwameistor_localdisk_capacity) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{status=\"Bound\"}) or vector(0)",
     "legendFormat": "Bound"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{status=\"Available\"}) or vector(0)",
     "legendFormat": "Available"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{status=\"Pending\"}) or vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "count(hwameistor_localdisk_capacity{reserved=\"true\"}) or vector(0)",
     "legendFormat": "Reseverd"
    }
   ]
  },
  {
   "title": "Disks Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "hwameistor_localdisk_capacity", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ata_smart_attribute{attribute_name=\"Temperature_Celsius\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Reallocated Sector Ct",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ata_smart_attribute{attribute_name=\"Reallocated_Sector_Ct\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "UDMA CRC Error Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ata_smart_attribute{attribute_name=\"UDMA_CRC_Error_Count\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Raw Read Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ata_smart_attribute{attribute_name=\"Raw_Read_Error_Rate\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Reallocated Event Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ata_smart_attribute{attribute_name=\"Reallocated_Event_Count\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}