// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// LocalDiskListerExpansion allows custom methods to be added to
// LocalDiskLister.
type LocalDiskListerExpansion interface{}

// LocalDiskClaimListerExpansion allows custom methods to be added to
// LocalDiskClaimLister.
type LocalDiskClaimListerExpansion interface{}

// LocalDiskNodeListerExpansion allows custom methods to be added to
// LocalDiskNodeLister.
type LocalDiskNodeListerExpansion interface{}

// LocalDiskVolumeListerExpansion allows custom methods to be added to
// LocalDiskVolumeLister.
type LocalDiskVolumeListerExpansion interface{}

// LocalStorageNodeListerExpansion allows custom methods to be added to
// LocalStorageNodeLister.
type LocalStorageNodeListerExpansion interface{}

// LocalVolumeListerExpansion allows custom methods to be added to
// LocalVolumeLister.
type LocalVolumeListerExpansion interface{}

// LocalVolumeConvertListerExpansion allows custom methods to be added to
// LocalVolumeConvertLister.
type LocalVolumeConvertListerExpansion interface{}

// LocalVolumeExpandListerExpansion allows custom methods to be added to
// LocalVolumeExpandLister.
type LocalVolumeExpandListerExpansion interface{}

// LocalVolumeGroupListerExpansion allows custom methods to be added to
// LocalVolumeGroupLister.
type LocalVolumeGroupListerExpansion interface{}

// LocalVolumeMigrateListerExpansion allows custom methods to be added to
// LocalVolumeMigrateLister.
type LocalVolumeMigrateListerExpansion interface{}

// LocalVolumeReplicaListerExpansion allows custom methods to be added to
// LocalVolumeReplicaLister.
type LocalVolumeReplicaListerExpansion interface{}
