// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalVolumeSnapshotLister helps list LocalVolumeSnapshots.
type LocalVolumeSnapshotLister interface {
	// List lists all LocalVolumeSnapshots in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.LocalVolumeSnapshot, err error)
	// LocalVolumeSnapshots returns an object that can list and get LocalVolumeSnapshots.
	LocalVolumeSnapshots(namespace string) LocalVolumeSnapshotNamespaceLister
	LocalVolumeSnapshotListerExpansion
}

// localVolumeSnapshotLister implements the LocalVolumeSnapshotLister interface.
type localVolumeSnapshotLister struct {
	indexer cache.Indexer
}

// NewLocalVolumeSnapshotLister returns a new LocalVolumeSnapshotLister.
func NewLocalVolumeSnapshotLister(indexer cache.Indexer) LocalVolumeSnapshotLister {
	return &localVolumeSnapshotLister{indexer: indexer}
}

// List lists all LocalVolumeSnapshots in the indexer.
func (s *localVolumeSnapshotLister) List(selector labels.Selector) (ret []*v1alpha1.LocalVolumeSnapshot, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalVolumeSnapshot))
	})
	return ret, err
}

// LocalVolumeSnapshots returns an object that can list and get LocalVolumeSnapshots.
func (s *localVolumeSnapshotLister) LocalVolumeSnapshots(namespace string) LocalVolumeSnapshotNamespaceLister {
	return localVolumeSnapshotNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// LocalVolumeSnapshotNamespaceLister helps list and get LocalVolumeSnapshots.
type LocalVolumeSnapshotNamespaceLister interface {
	// List lists all LocalVolumeSnapshots in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.LocalVolumeSnapshot, err error)
	// Get retrieves the LocalVolumeSnapshot from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.LocalVolumeSnapshot, error)
	LocalVolumeSnapshotNamespaceListerExpansion
}

// localVolumeSnapshotNamespaceLister implements the LocalVolumeSnapshotNamespaceLister
// interface.
type localVolumeSnapshotNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all LocalVolumeSnapshots in the indexer for a given namespace.
func (s localVolumeSnapshotNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.LocalVolumeSnapshot, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalVolumeSnapshot))
	})
	return ret, err
}

// Get retrieves the LocalVolumeSnapshot from the indexer for a given namespace and name.
func (s localVolumeSnapshotNamespaceLister) Get(name string) (*v1alpha1.LocalVolumeSnapshot, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("localvolumesnapshot"), name)
	}
	return obj.(*v1alpha1.LocalVolumeSnapshot), nil
}
