// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalStorageNodeLister helps list LocalStorageNodes.
// All objects returned here must be treated as read-only.
type LocalStorageNodeLister interface {
	// List lists all LocalStorageNodes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LocalStorageNode, err error)
	// Get retrieves the LocalStorageNode from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LocalStorageNode, error)
	LocalStorageNodeListerExpansion
}

// localStorageNodeLister implements the LocalStorageNodeLister interface.
type localStorageNodeLister struct {
	indexer cache.Indexer
}

// NewLocalStorageNodeLister returns a new LocalStorageNodeLister.
func NewLocalStorageNodeLister(indexer cache.Indexer) LocalStorageNodeLister {
	return &localStorageNodeLister{indexer: indexer}
}

// List lists all LocalStorageNodes in the indexer.
func (s *localStorageNodeLister) List(selector labels.Selector) (ret []*v1alpha1.LocalStorageNode, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalStorageNode))
	})
	return ret, err
}

// Get retrieves the LocalStorageNode from the index for a given name.
func (s *localStorageNodeLister) Get(name string) (*v1alpha1.LocalStorageNode, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("localstoragenode"), name)
	}
	return obj.(*v1alpha1.LocalStorageNode), nil
}
