// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalDiskLister helps list LocalDisks.
// All objects returned here must be treated as read-only.
type LocalDiskLister interface {
	// List lists all LocalDisks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LocalDisk, err error)
	// Get retrieves the LocalDisk from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LocalDisk, error)
	LocalDiskListerExpansion
}

// localDiskLister implements the LocalDiskLister interface.
type localDiskLister struct {
	indexer cache.Indexer
}

// NewLocalDiskLister returns a new LocalDiskLister.
func NewLocalDiskLister(indexer cache.Indexer) LocalDiskLister {
	return &localDiskLister{indexer: indexer}
}

// List lists all LocalDisks in the indexer.
func (s *localDiskLister) List(selector labels.Selector) (ret []*v1alpha1.LocalDisk, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalDisk))
	})
	return ret, err
}

// Get retrieves the LocalDisk from the index for a given name.
func (s *localDiskLister) Get(name string) (*v1alpha1.LocalDisk, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("localdisk"), name)
	}
	return obj.(*v1alpha1.LocalDisk), nil
}
