// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalDiskClaimLister helps list LocalDiskClaims.
// All objects returned here must be treated as read-only.
type LocalDiskClaimLister interface {
	// List lists all LocalDiskClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LocalDiskClaim, err error)
	// Get retrieves the LocalDiskClaim from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LocalDiskClaim, error)
	LocalDiskClaimListerExpansion
}

// localDiskClaimLister implements the LocalDiskClaimLister interface.
type localDiskClaimLister struct {
	indexer cache.Indexer
}

// NewLocalDiskClaimLister returns a new LocalDiskClaimLister.
func NewLocalDiskClaimLister(indexer cache.Indexer) LocalDiskClaimLister {
	return &localDiskClaimLister{indexer: indexer}
}

// List lists all LocalDiskClaims in the indexer.
func (s *localDiskClaimLister) List(selector labels.Selector) (ret []*v1alpha1.LocalDiskClaim, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalDiskClaim))
	})
	return ret, err
}

// Get retrieves the LocalDiskClaim from the index for a given name.
func (s *localDiskClaimLister) Get(name string) (*v1alpha1.LocalDiskClaim, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("localdiskclaim"), name)
	}
	return obj.(*v1alpha1.LocalDiskClaim), nil
}
