// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalVolumeGroupMigrateLister helps list LocalVolumeGroupMigrates.
type LocalVolumeGroupMigrateLister interface {
	// List lists all LocalVolumeGroupMigrates in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.LocalVolumeGroupMigrate, err error)
	// Get retrieves the LocalVolumeGroupMigrate from the index for a given name.
	Get(name string) (*v1alpha1.LocalVolumeGroupMigrate, error)
	LocalVolumeGroupMigrateListerExpansion
}

// localVolumeGroupMigrateLister implements the LocalVolumeGroupMigrateLister interface.
type localVolumeGroupMigrateLister struct {
	indexer cache.Indexer
}

// NewLocalVolumeGroupMigrateLister returns a new LocalVolumeGroupMigrateLister.
func NewLocalVolumeGroupMigrateLister(indexer cache.Indexer) LocalVolumeGroupMigrateLister {
	return &localVolumeGroupMigrateLister{indexer: indexer}
}

// List lists all LocalVolumeGroupMigrates in the indexer.
func (s *localVolumeGroupMigrateLister) List(selector labels.Selector) (ret []*v1alpha1.LocalVolumeGroupMigrate, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalVolumeGroupMigrate))
	})
	return ret, err
}

// Get retrieves the LocalVolumeGroupMigrate from the index for a given name.
func (s *localVolumeGroupMigrateLister) Get(name string) (*v1alpha1.LocalVolumeGroupMigrate, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("localvolumegroupmigrate"), name)
	}
	return obj.(*v1alpha1.LocalVolumeGroupMigrate), nil
}
