// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/hwameistor/pkg/apis/hwameistor/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LocalDiskVolumeLister helps list LocalDiskVolumes.
// All objects returned here must be treated as read-only.
type LocalDiskVolumeLister interface {
	// List lists all LocalDiskVolumes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LocalDiskVolume, err error)
	// Get retrieves the LocalDiskVolume from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LocalDiskVolume, error)
	LocalDiskVolumeListerExpansion
}

// localDiskVolumeLister implements the LocalDiskVolumeLister interface.
type localDiskVolumeLister struct {
	indexer cache.Indexer
}

// NewLocalDiskVolumeLister returns a new LocalDiskVolumeLister.
func NewLocalDiskVolumeLister(indexer cache.Indexer) LocalDiskVolumeLister {
	return &localDiskVolumeLister{indexer: indexer}
}

// List lists all LocalDiskVolumes in the indexer.
func (s *localDiskVolumeLister) List(selector labels.Selector) (ret []*v1alpha1.LocalDiskVolume, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LocalDiskVolume))
	})
	return ret, err
}

// Get retrieves the LocalDiskVolume from the index for a given name.
func (s *localDiskVolumeLister) Get(name string) (*v1alpha1.LocalDiskVolume, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("localdiskvolume"), name)
	}
	return obj.(*v1alpha1.LocalDiskVolume), nil
}
