apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base-2
namespace: s1
patchesStrategicMerge:
  - tenant.yaml
patchesJson6902:
  - target:
      group: minio.min.io
      version: v2
      kind: Tenant
      name: minio-t2
    path: tenantNamePatch.yaml
