// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type LocalStorageAlertExpansion interface{}

type LocalStorageNodeExpansion interface{}

type LocalVolumeExpansion interface{}

type LocalVolumeExpandExpansion interface{}

type LocalVolumeReplicaExpansion interface{}

type PhysicalDiskExpansion interface{}
