// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	scheme "github.com/hwameistor/local-storage/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/local-storage/pkg/apis/localstorage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalStorageAlertsGetter has a method to return a LocalStorageAlertInterface.
// A group's client should implement this interface.
type LocalStorageAlertsGetter interface {
	LocalStorageAlerts() LocalStorageAlertInterface
}

// LocalStorageAlertInterface has methods to work with LocalStorageAlert resources.
type LocalStorageAlertInterface interface {
	Create(ctx context.Context, localStorageAlert *v1alpha1.LocalStorageAlert, opts v1.CreateOptions) (*v1alpha1.LocalStorageAlert, error)
	Update(ctx context.Context, localStorageAlert *v1alpha1.LocalStorageAlert, opts v1.UpdateOptions) (*v1alpha1.LocalStorageAlert, error)
	UpdateStatus(ctx context.Context, localStorageAlert *v1alpha1.LocalStorageAlert, opts v1.UpdateOptions) (*v1alpha1.LocalStorageAlert, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LocalStorageAlert, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LocalStorageAlertList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalStorageAlert, err error)
	LocalStorageAlertExpansion
}

// localStorageAlerts implements LocalStorageAlertInterface
type localStorageAlerts struct {
	client rest.Interface
}

// newLocalStorageAlerts returns a LocalStorageAlerts
func newLocalStorageAlerts(c *LocalStorageV1alpha1Client) *localStorageAlerts {
	return &localStorageAlerts{
		client: c.RESTClient(),
	}
}

// Get takes name of the localStorageAlert, and returns the corresponding localStorageAlert object, and an error if there is any.
func (c *localStorageAlerts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LocalStorageAlert, err error) {
	result = &v1alpha1.LocalStorageAlert{}
	err = c.client.Get().
		Resource("localstoragealerts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalStorageAlerts that match those selectors.
func (c *localStorageAlerts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LocalStorageAlertList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LocalStorageAlertList{}
	err = c.client.Get().
		Resource("localstoragealerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localStorageAlerts.
func (c *localStorageAlerts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localstoragealerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localStorageAlert and creates it.  Returns the server's representation of the localStorageAlert, and an error, if there is any.
func (c *localStorageAlerts) Create(ctx context.Context, localStorageAlert *v1alpha1.LocalStorageAlert, opts v1.CreateOptions) (result *v1alpha1.LocalStorageAlert, err error) {
	result = &v1alpha1.LocalStorageAlert{}
	err = c.client.Post().
		Resource("localstoragealerts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localStorageAlert).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localStorageAlert and updates it. Returns the server's representation of the localStorageAlert, and an error, if there is any.
func (c *localStorageAlerts) Update(ctx context.Context, localStorageAlert *v1alpha1.LocalStorageAlert, opts v1.UpdateOptions) (result *v1alpha1.LocalStorageAlert, err error) {
	result = &v1alpha1.LocalStorageAlert{}
	err = c.client.Put().
		Resource("localstoragealerts").
		Name(localStorageAlert.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localStorageAlert).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localStorageAlerts) UpdateStatus(ctx context.Context, localStorageAlert *v1alpha1.LocalStorageAlert, opts v1.UpdateOptions) (result *v1alpha1.LocalStorageAlert, err error) {
	result = &v1alpha1.LocalStorageAlert{}
	err = c.client.Put().
		Resource("localstoragealerts").
		Name(localStorageAlert.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localStorageAlert).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localStorageAlert and deletes it. Returns an error if one occurs.
func (c *localStorageAlerts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localstoragealerts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localStorageAlerts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localstoragealerts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localStorageAlert.
func (c *localStorageAlerts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LocalStorageAlert, err error) {
	result = &v1alpha1.LocalStorageAlert{}
	err = c.client.Patch(pt).
		Resource("localstoragealerts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
