// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/hwameistor/local-storage/pkg/apis/client/clientset/versioned/scheme"
	v1alpha1 "github.com/hwameistor/local-storage/pkg/apis/localstorage/v1alpha1"
	rest "k8s.io/client-go/rest"
)

type LocalStorageV1alpha1Interface interface {
	RESTClient() rest.Interface
	LocalStorageAlertsGetter
	LocalStorageNodesGetter
	LocalVolumesGetter
	LocalVolumeExpandsGetter
	LocalVolumeReplicasGetter
	PhysicalDisksGetter
}

// LocalStorageV1alpha1Client is used to interact with features provided by the localstorage.hwameistor.io group.
type LocalStorageV1alpha1Client struct {
	restClient rest.Interface
}

func (c *LocalStorageV1alpha1Client) LocalStorageAlerts() LocalStorageAlertInterface {
	return newLocalStorageAlerts(c)
}

func (c *LocalStorageV1alpha1Client) LocalStorageNodes() LocalStorageNodeInterface {
	return newLocalStorageNodes(c)
}

func (c *LocalStorageV1alpha1Client) LocalVolumes() LocalVolumeInterface {
	return newLocalVolumes(c)
}

func (c *LocalStorageV1alpha1Client) LocalVolumeExpands() LocalVolumeExpandInterface {
	return newLocalVolumeExpands(c)
}

func (c *LocalStorageV1alpha1Client) LocalVolumeReplicas() LocalVolumeReplicaInterface {
	return newLocalVolumeReplicas(c)
}

func (c *LocalStorageV1alpha1Client) PhysicalDisks() PhysicalDiskInterface {
	return newPhysicalDisks(c)
}

// NewForConfig creates a new LocalStorageV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*LocalStorageV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &LocalStorageV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new LocalStorageV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *LocalStorageV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new LocalStorageV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *LocalStorageV1alpha1Client {
	return &LocalStorageV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *LocalStorageV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
