// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/hwameistor/local-storage/pkg/apis/localstorage/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PhysicalDiskLister helps list PhysicalDisks.
type PhysicalDiskLister interface {
	// List lists all PhysicalDisks in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.PhysicalDisk, err error)
	// Get retrieves the PhysicalDisk from the index for a given name.
	Get(name string) (*v1alpha1.PhysicalDisk, error)
	PhysicalDiskListerExpansion
}

// physicalDiskLister implements the PhysicalDiskLister interface.
type physicalDiskLister struct {
	indexer cache.Indexer
}

// NewPhysicalDiskLister returns a new PhysicalDiskLister.
func NewPhysicalDiskLister(indexer cache.Indexer) PhysicalDiskLister {
	return &physicalDiskLister{indexer: indexer}
}

// List lists all PhysicalDisks in the indexer.
func (s *physicalDiskLister) List(selector labels.Selector) (ret []*v1alpha1.PhysicalDisk, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PhysicalDisk))
	})
	return ret, err
}

// Get retrieves the PhysicalDisk from the index for a given name.
func (s *physicalDiskLister) Get(name string) (*v1alpha1.PhysicalDisk, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("physicaldisk"), name)
	}
	return obj.(*v1alpha1.PhysicalDisk), nil
}
