ALERTER_NAME = dce-uds-local-storage-alerter
ALERTER_IMAGE_DIR = ${PROJECT_SOURCE_CODE_DIR}/images/alerter
ALERTER_BUILD_BIN = ${BINS_DIR}/${ALERTER_NAME}-run
ALERTER_BUILD_MAIN = ${CMDS_DIR}/alerter/main.go

ALERTER_IMAGE_NAME = ${DOCKER_REGISTRY}/${ALERTER_NAME}
RELEASE_ALERTER_IMAGE_NAME=${RELEASE_DOCKER_REGISTRY}/${ALERTER_NAME}

.PHONY: alerter_run
alerter_run:
	${RUN_CMD} ${BUILD_OPTIONS} ${ALERTER_BUILD_MAIN}

.PHONY: alerter
alerter:
	GOARCH=amd64 ${BUILD_ENVS} ${BUILD_CMD} ${BUILD_OPTIONS} -o ${ALERTER_BUILD_BIN} ${ALERTER_BUILD_MAIN}

.PHONY: alerter_arm64
alerter_arm64:
	GOARCH=arm64 ${BUILD_ENVS} ${BUILD_CMD} ${BUILD_OPTIONS} -o ${ALERTER_BUILD_BIN} ${ALERTER_BUILD_MAIN}

.PHONY: alerter_image
alerter_image:
	${DOCKER_MAKE_CMD} make alerter
	docker build -t ${ALERTER_IMAGE_NAME}:${IMAGE_TAG} -f ${ALERTER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	docker push ${ALERTER_IMAGE_NAME}:${IMAGE_TAG}

.PHONY: alerter_release
alerter_release:
	# build for amd64 version
	${DOCKER_MAKE_CMD} make alerter
	${DOCKER_BUILDX_CMD_AMD64} -t ${RELEASE_ALERTER_IMAGE_NAME}:${RELEASE_TAG}-amd64 -f ${ALERTER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	# build for arm64 version
	${DOCKER_MAKE_CMD} make alerter_arm64
	${DOCKER_BUILDX_CMD_ARM64} -t ${RELEASE_ALERTER_IMAGE_NAME}:${RELEASE_TAG}-arm64 -f ${ALERTER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	# push to a public registry
	${MUILT_ARCH_PUSH_CMD} ${RELEASE_ALERTER_IMAGE_NAME}:${RELEASE_TAG}
