DISK_CHECKER_NAME = dce-uds-disk-checker
DISK_CHECKER_IMAGE_DIR = ${PROJECT_SOURCE_CODE_DIR}/images/disk-checker
DISK_CHECKER_BUILD_BIN = ${BINS_DIR}/${DISK_CHECKER_NAME}-run
DISK_CHECKER_BUILD_MAIN = ${CMDS_DIR}/disk-checker/main.go

DISK_CHECKER_IMAGE_NAME = ${DOCKER_REGISTRY}/${DISK_CHECKER_NAME}
RELEASE_DISK_CHECKER_IMAGE_NAME=${RELEASE_DOCKER_REGISTRY}/${DISK_CHECKER_NAME}

.PHONY: disk_checker
disk_checker:
	GOARCH=amd64 ${BUILD_ENVS} ${BUILD_CMD} ${BUILD_OPTIONS} -o ${DISK_CHECKER_BUILD_BIN} ${DISK_CHECKER_BUILD_MAIN}

.PHONY: disk_checker_arm64
disk_checker_arm64:
	GOARCH=arm64 ${BUILD_ENVS} ${BUILD_CMD} ${BUILD_OPTIONS} -o ${DISK_CHECKER_BUILD_BIN} ${DISK_CHECKER_BUILD_MAIN}

.PHONY: disk_checker_image
disk_checker_image:
	${DOCKER_MAKE_CMD} make disk_checker
	docker build -t ${DISK_CHECKER_IMAGE_NAME}:${IMAGE_TAG} -f ${DISK_CHECKER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	docker push ${DISK_CHECKER_IMAGE_NAME}:${IMAGE_TAG}

.PHONY: disk_checker_release
disk_checker_release:
	# build for amd64 version
	${DOCKER_MAKE_CMD} make disk_checker
	${DOCKER_BUILDX_CMD_AMD64} -t ${RELEASE_DISK_CHECKER_IMAGE_NAME}:${RELEASE_TAG}-amd64 -f ${DISK_CHECKER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	# build for arm64 version
	${DOCKER_MAKE_CMD} make disk_checker_arm64
	${DOCKER_BUILDX_CMD_ARM64} -t ${RELEASE_DISK_CHECKER_IMAGE_NAME}:${RELEASE_TAG}-arm64 -f ${DISK_CHECKER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	# push to a public registry
	${MUILT_ARCH_PUSH_CMD} ${RELEASE_DISK_CHECKER_IMAGE_NAME}:${RELEASE_TAG}
