SCHEDULER_NAME = local-storage-scheduler
SCHEDULER_IMAGE_DIR = ${PROJECT_SOURCE_CODE_DIR}/images/scheduler
SCHEDULER_BUILD_BIN = ${BINS_DIR}/${SCHEDULER_NAME}-run
SCHEDULER_BUILD_MAIN = ${CMDS_DIR}/scheduler/main.go

SCHEDULER_IMAGE_NAME = ${DOCKER_REGISTRY}/${SCHEDULER_NAME}
RELEASE_SCHEDULER_IMAGE_NAME=${RELEASE_DOCKER_REGISTRY}/${SCHEDULER_NAME}

.PHONY: scheduler
scheduler:
	GOARCH=amd64 ${BUILD_ENVS} ${BUILD_CMD} ${BUILD_OPTIONS} -o ${SCHEDULER_BUILD_BIN} ${SCHEDULER_BUILD_MAIN}

.PHONY: scheduler_arm64
scheduler_arm64:
	GOARCH=arm64 ${BUILD_ENVS} ${BUILD_CMD} ${BUILD_OPTIONS} -o ${SCHEDULER_BUILD_BIN} ${SCHEDULER_BUILD_MAIN}

.PHONY: scheduler_image
scheduler_image: 
	${DOCKER_MAKE_CMD} make scheduler
	docker build -t ${SCHEDULER_IMAGE_NAME}:${IMAGE_TAG} -f ${SCHEDULER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	docker push ${SCHEDULER_IMAGE_NAME}:${IMAGE_TAG}

.PHONY: scheduler_release
scheduler_release: 
	# build for amd64 version
	${DOCKER_MAKE_CMD} make scheduler
	${DOCKER_BUILDX_CMD_AMD64} -t ${RELEASE_SCHEDULER_IMAGE_NAME}:${RELEASE_TAG}-amd64 -f ${SCHEDULER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	# build for arm64 version
	${DOCKER_MAKE_CMD} make scheduler_arm64
	${DOCKER_BUILDX_CMD_ARM64} -t ${RELEASE_SCHEDULER_IMAGE_NAME}:${RELEASE_TAG}-arm64 -f ${SCHEDULER_IMAGE_DIR}/Dockerfile ${PROJECT_SOURCE_CODE_DIR}
	# push to a public registry
	${MUILT_ARCH_PUSH_CMD} ${RELEASE_SCHEDULER_IMAGE_NAME}:${RELEASE_TAG}
