name: Adaptation-test-new

on:
  workflow_dispatch:
    inputs:
      k8s-version:
        description: 'choice'
        required: false
        default: 'ALL'
        type: choice
        options:
          - ALL
          - k8s1.25.3 & kylin10_arm
          - k8s1.24.0 & centos7.6
          - k8s1.25.0 & centos7.6
          - k8s1.26.0 & centos7.6
          - k8s1.27.0 & centos7.6
          - k8s1.28.0 & centos7.6
          - k8s1.29.0 & centos7.6
          #         - k8s1.23.3 & centos7.9
          - k8s1.28.0 & centos8.1
          - k8s1.28.0 & ubuntu2204
#         - k8s1.23.3 & centos7.9_offline


jobs:
  build_test_image:
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build test image
        run: make make_test_image
  ad_test:
    runs-on: ["e2e"]
    needs: [build_test_image]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/_build
          sudo rm -rf /github/actions-runner/_work/hwameistor/hwameistor/test/e2e/drbd-adapter/
          sudo rm -rf /home/github/actions-runner/_work/hwameistor/hwameistor/_build/
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: make adaptation test
        env:
          E2E_TESTING_LEVEL: "k8s1.26"
        run: make adaptation_test
