name: HwameiStor PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "pkg/**"
      - "cmd/**"
      - "test/**"
      - "build/**"
      - "helm/**"
      - "deploy/**"
      - ".github/**"

jobs:
  pr-test:
    runs-on: ["e2e"]
    timeout-minutes: 180
    steps:
      - name: delete
        run: |
          docker version
